import React, { createContext, useContext, useEffect, useState } from 'react';
import { Post } from '../types';

interface BlogContextType {
    posts: Post[];
    loading: boolean;
    getPostById: (id: string) => Post | undefined;
}

const BlogContext = createContext<BlogContextType>({
    posts: [],
    loading: true,
    getPostById: () => undefined,
});

export const BlogProvider = ({ children }: { children: React.ReactNode }) => {
    const [posts, setPosts] = useState<Post[]>([]);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        const fetchPosts = async () => {
            try {
                // Fetch the JSON API generated by Node script
                // Use default /api/posts.json assuming root deployment, or prepend base
                const response = await fetch('/api/posts.json');
                if (response.ok) {
                    const data = await response.json();
                    setPosts(data);
                } else {
                    console.error("Failed to fetch posts from api/posts.json");
                }
            } catch (error) {
                console.error("Error fetching blog posts:", error);
            } finally {
                setLoading(false);
            }
        };

        fetchPosts();
    }, []);

    // Helper to find a post. We match loosely on the URL part or ID
    const getPostById = (id: string) => {
        return posts.find(p => p.id.includes(id) || p.title.toLowerCase().replace(/\s+/g, '-') === id);
    };

    return (
        <BlogContext.Provider value={{ posts, loading, getPostById }}>
            {children}
        </BlogContext.Provider>
    );
};

export const useBlog = () => useContext(BlogContext);
